import streamlit as st
from huggingface_hub import InferenceClient
import time

# ==========================================
# 1. KONFIGURASI HALAMAN
# ==========================================
st.set_page_config(page_title="Magic Ad Generator", page_icon="✨")

st.title("✨ AI Creative Assistant")
st.write("Bikin ide iklan + gambar visual cuma dalam 1 klik!")


HF_TOKEN = st.secrets["HF_TOKEN"]

# ==========================================
# 2. SETUP MODEL (Siapkan Karyawan AI)
# ==========================================
# Karyawan 1: Penulis Naskah (Qwen)
repo_id_text = "Qwen/Qwen2.5-72B-Instruct"
llm_client = InferenceClient(model=repo_id_text, token=HF_TOKEN)

# Karyawan 2: Pelukis (Stable Diffusion XL)
repo_id_image = "stabilityai/stable-diffusion-xl-base-1.0"
image_client = InferenceClient(model=repo_id_image, token=HF_TOKEN)

# ==========================================
# 3. AREA INTERAKSI USER
# ==========================================
col1, col2 = st.columns(2)

with col1:
    product_name = st.text_input("Nama Produk", placeholder="Contoh: Keripik Singkong Pedas")

with col2:
    vibe = st.text_input("Target Audience / Vibe", placeholder="Contoh: Nongkrong malam minggu")

# Tombol Ajaib
if st.button("Generate Magic! 🚀"):
    if not product_name or not vibe:
        st.warning("Isi dulu nama produk dan vibe-nya dong bos! 😅")
    else:
        try:
            # --- LANGKAH 1: PIKIRKAN IDE (TEXT GENERATION) ---
            with st.spinner("Sedang memeras otak cari ide caption... 🧠"):
                
                # Mantera untuk si Penulis
                prompt_text = f"""
                You are an expert Creative Director.
                User Input: Product: {product_name}, Vibe: {vibe}.
                Output format must be exactly:
                [Instagram Caption with emojis]
                ###
                [Detailed English Image Prompt for Stable Diffusion, no text in image]
                """
                
                messages = [{"role": "user", "content": prompt_text}]
                response = llm_client.chat_completion(messages, max_tokens=500)
                full_text = response.choices[0].message.content
                
                # Pisahkan Caption dan Prompt Gambar pakai tanda "###"
                parts = full_text.split("###")
                
                if len(parts) < 2:
                    st.error("Waduh, AI-nya bingung misahin output. Coba lagi ya!")
                    st.stop()
                
                caption = parts[0].replace("[", "").replace("]", "").strip() # Bersihin tanda kurung
                image_prompt = parts[1].replace("[", "").replace("]", "").strip()

            # --- LANGKAH 2: GAMBAR VISUAL (IMAGE GENERATION) ---
            with st.spinner("Sedang melukis gambar produk... 🎨"):
                image = image_client.text_to_image(image_prompt)
            
            # --- LANGKAH 3: TAMPILKAN HASIL ---
            st.success("Selesai! 🎉")
            
            # Tampilkan Gambar
            st.image(image, caption="Visual Generated by AI", use_column_width=True)
            
            # Tampilkan Caption
            st.subheader("📝 Ide Caption:")
            st.text_area("Copy caption ini:", value=caption, height=150)

            # Tampilkan Prompt Gambar
            with st.expander("Lihat Prompt Rahasia Dibalik Layar"):
                st.write(image_prompt)

        except Exception as e:
            st.error(f"Yah error: {e}")